version: "3.9"

services:
  api:
    build:
      context: ./portal-aulas-api
      dockerfile: development.dockerfile
    image: portal-aulas-api:1.0
    container_name: portal-aulas-api
    volumes:
      - ./portal-aulas-api:/app
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db
    command: sh -c "python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8080"

  db:
    build:
      context: .
      dockerfile: ./dev-database.dockerfile
    image: portal-aulas-database
    container_name: portal-aulas-database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"

volumes:
  postgres-data:


# docker exec -it portal-aulas-api sh -c "python /app/manage.py makemigrations && python /app/manage.py migrate"

# docker exec -it portal-aulas-api sh -c "COMAND"